### ISSUE TITLE
Add leases to CAS

### ISSUE THREAD

**Issue by vykster** [OpenHousing/boston-cas#12]
Needs to be in CAS.

Lease has:
+ lease_id (primary key) currently generated by an outside system called elite
+ rent_total (number, us dollars)
+ rent_programpaid 
+ rent_tenantpaid
+ payee_id
+ owner_id 
+ lease_ update (date)

to be implemented later:
+ relationship to vouchers.
+ relationship to buildings
+ owners
+ payees

open questions:
+ how to link to mobile vouchers
+ how to link to buildings

**Comment by repp** [comment]
Is there ever a situation where rent_programpaid + rent_tenantpaid != rent_total? Do we need all 3 fields or can we always infer one from the other two? 

Are owner and payee other models that already exist in CAS (i.e 'Client') that I should connect Leases to? Are they new models that I should stub out?

Is lease_update always manually entered or does it just automatically update everytime a record is changed?

Do we need a full CRUD interface for leases and/or are they coming from an external data source? Both?

**Comment by repp** [comment]
*I should have read the owner task first.

**Comment by vykster** [comment]
> Do we need a full CRUD interface for leases and/or are they coming from an external data source? Both?

Probably both here, a very simple CRUD UI.

You are right on rent_programpaid + rent_tenantpaid != rent_total?, let's keep total and program paid and infer tenant paid for now. Total is likely to be the most reliable number, and least likely to change.

**Comment by repp** [comment]
Leases are up: https://saltlakecounty-housing.brighthive.io/leases Is there anything else I can add at this point? Anything that should be changed?

**Comment by vykster** [comment]
On this page, https://saltlakecounty-housing.brighthive.io/leases

let's also display tenant paid + program paid.

The lease_ update should actually be the date the lease is valid until, not a updated rails datestamp. Could you confirm it is and change the label to "Leased through"

I'll prep and send you data for leases today.

**Comment by repp** [comment]
Done. The lease_update field is just a normal date field that gets manually entered and updated, it's not the default rails model updated_at field.

**Comment by repp** [comment]
Leases and owners are all imported. Let me know if I should change/update anything.
