### ISSUE TITLE
Add owners to CAS

### ISSUE THREAD

**Issue by vykster** [OpenHousing/boston-cas#13]
Owner has:
+ owner_id (primary key, currently generated by outside system)
+ name (string ex: "Grace Mary Manor, LLC")
+ address (please copy implementation style of address for building ie single field or multiple for city, state, zip.)
+ phone  (please copy implementation style of any phone number fields already in the app)

**Comment by vykster** [comment]
There is already a "contacts" concept, attached to buildings. Please extend this to work as an owner.

**Comment by vykster** [comment]
Let me know if you want to talk through this at all. @repp

**Comment by repp** [comment]
Is an owner's address potentially different than the address of the building they're attached to? 

If I add a special owner_id (and maybe address) field(s) to building contacts and then attach owners (aka building contacts) to leases will that work?

**Comment by vykster** [comment]
Yes, an owner's address can be different than the building and frequently is. 

We might not be able to extend contacts to do this easily

**Comment by repp** [comment]
Done (I think). Check out: https://saltlakecounty-housing.brighthive.io/buildings/1/contacts and let me know what you think.

**Comment by vykster** [comment]
Looks good.
