### ISSUE TITLE
Seeds client data

### ISSUE THREAD

**Issue by vykster** [OpenHousing/boston-cas#4]
Create seeds file for fake client data for testing app.

**Comment by repp** [comment]
Done.

**Comment by vykster** [comment]
@repp We need to be able to test and interact with the matching functions, it seems more client info is needed in test data to do this. 

https://saltlakecounty-housing.brighthive.io/active_matches

**Comment by repp** [comment]
Should be fixed now. I was able to move a client all the way through the process and reject a different client. 

To make the match process work:
1. Make sure at least one client's 'available' attribute is set to true
2. Submit a new vacancy which kicks off the matching engine job

I also fixed two really minor UI bugs in the process.

**Comment by vykster** [comment]
@repp what's your process, are you committing code locally? 

Also would you update this repo from upstream? I'd like us to start investigating the new routes feature Green River merged.

**Comment by vykster** [comment]
Also once you've merged from upstream would you create a PR to greenriver/boston-cas for fixing the client seeds file?

**Comment by repp** [comment]
I started my own fork before I knew about this one. (https://github.com/repp/salt-lake-county-cas) I'll get everything merged together and updated today.

**Comment by repp** [comment]
New routes feature is up: https://saltlakecounty-housing.brighthive.io/admin/match_routes Working on moving my work to this repo and then the PR.

**Comment by repp** [comment]
OpenHousing Repo is updated. PR Submitted: https://github.com/greenriver/boston-cas/pull/100
