### ISSUE TITLE
Import HMIS HUD csv sample data

### ISSUE THREAD

**Issue by vykster** [OpenHousing/boston-cas#6]

**Comment by vykster** [comment]
queued, UI does not show status of import. How could we show status of import?

**Comment by repp** [comment]
I'd misconfigured delayed_job on the aws server so there weren't any workers running and the import status just sat as 'incomplete'. When the import gets picked up by a worker, it updates the status:

<img width="1434" alt="screen shot 2018-06-14 at 4 35 43 pm" src="https://user-images.githubusercontent.com/2077986/41437448-7a62572a-6ff2-11e8-8a6f-a535814bafb7.png">
