### ISSUE TITLE
[warehouse] Hide Health Reports when Healthcare section is not enabled

### ISSUE THREAD

**Issue by vykster** [OpenHousing/boston-cas#7]
Hide [Health Reports tab](https://saltlakecounty-warehouse.brighthive.io/warehouse_reports#health) when [Healthcare section is not enabled](https://saltlakecounty-warehouse.brighthive.io/admin/configs)

Please push fix upstream too.

**Comment by repp** [comment]
Fixed it on the live site, still need to push upstream.

**Comment by repp** [comment]
PR submitted: https://github.com/greenriver/hmis-warehouse/pull/238

**Comment by repp** [comment]
The git history on the old PR got really crufty. New PR is here: https://github.com/greenriver/hmis-warehouse/pull/241

**Comment by repp** [comment]
PR was merged.
